repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        stages: [pre-commit]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest-cov
        name: Run tests
        entry: poetry run --directory ./lab3 pytest --cov --cov-report=term-missing --cov-report=html:.coverage-html --cov-fail-under=100
        files: ^tests/.*\.py$
        verbose: true
        types: [python]
        language: system
        stages: [pre-commit]
